### ISSUE TITLE
Minimal glitch: Translation for "or"

### ISSUE THREAD

**Issue by haslinger** [Hobo/hobo_bootstrap#42]
Line 54 of taglibs/login.dryml should read
```html
      <if test="&forgot_password_url"><t key="hobo.support.or">or</t> <a href="&forgot_password_url" param="forgot-password"><t key="hobo.login.forgot_password">Forgot your password?</t></a></if>
```
to have the "or" translated as well, instead of the current version
```html
      <if test="&forgot_password_url">or <a href="&forgot_password_url" param="forgot-password"><t key="hobo.login.forgot_password">Forgot your password?</t></a></if>
```

Sorry not to provide a proper pull request, I have a mess here with my current version for bootstrap 3. 
But I will fix that soon and give back to the community.

**Comment by iox** [comment]
Thanks Stefan! I just updated master.
